drop table PLAYER_INFO;
drop table POSITION;
drop table PLAYER_STATS;

CREATE TABLE Player_Info (
    Player_id INT PRIMARY KEY,
    PLAYER VARCHAR(50),
    TEAM VARCHAR(25),
    AGE INT
);


CREATE TABLE POSITION (
	POSITION VARCHAR(5),
	TEAM VARCHAR(25)
);


CREATE TABLE Player_Stats (
	PLAYER_id INT PRIMARY KEY,
	TOUCHES INT, 
	DRIBBLES_COMPLETED INT, 
	GOALS INT, 
	SHOTS INT, 
	SHOTS_ON_TARGET INT, 
	PASSES_COMPLETED INT, 
	PASSES INT, 
	ASSISTS INT, 
	TACKLES_WON INT
);

Select * from player_info;
select * from position;
select * from player_stats;




