drop table PLAYER_INFO;
drop table POSITION;
drop table PLAYER_STATS;

CREATE TABLE Player_Info (
    PLAYER_id INT PRIMARY KEY,
    POSITION_id INT,
    PLAYER VARCHAR(50),
    TEAM VARCHAR(25),
    AGE INT,
	value_in_Euros INT,
	"OVERALL_0-100" INT,
	MINUTES_PLAYED INT,
    FOREIGN KEY (Position_id) REFERENCES POSITION(Position_id)
);


CREATE TABLE POSITION (
	POSITION_id INT PRIMARY KEY,
	POSITION VARCHAR(5),
	TEAM VARCHAR(25),
	TOUCHES INT
);


CREATE TABLE Player_Stats (
	PLAYER_id INT PRIMARY KEY, 
	DRIBBLES_COMPLETED INT, 
	GOALS INT, 
	SHOTS INT, 
	SHOTS_ON_TARGET INT, 
	PASSES_COMPLETED INT, 
	PASSES INT, 
	ASSISTS INT, 
	TACKLES_WON INT
);

Select * from player_info;
select * from position;
select * from player_stats;




